# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks

compactor:
  config:
    compaction:
      block_retention: 2160h #2160 hours in 90 days
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  resources:
    limits:
      memory: 1536Mi
    requests:
      memory: 162Mi

distributor:
  config:
    max_attribute_bytes: 4096
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  resources:
    limits:
      memory: 320Mi
    requests:
      memory: 49Mi

ingester:
  persistence:
    enabled: true
    storageClass: csi-cinder-high-speed-retain
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: ingester
              app.kubernetes.io/instance: tempo-distributed
              app.kubernetes.io/name: tempo
          topologyKey: "kubernetes.io/hostname"
  resources:
    limits:
      memory: 2648Mi
    requests:
      memory: 45Mi

metricsGenerator:
  enabled: true
  kind: StatefulSet
  persistence:
    enabled: true
    storageClass: csi-cinder-high-speed-retain
  config:
    storage:
      remote_write:
        - url: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/prometheus/api/v1/write"
    processor:
      local_blocks:
        filter_server_spans: false
        flush_to_storage: true
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  resources:
    limits:
      memory: 1152Mi
    requests:
      memory: 261Mi

querier:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  resources:
    limits:
      memory: 992Mi
    requests:
      memory: 42Mi

queryFrontend:
  query:
    enabled: true
    resources:
      limits:
        memory: 6Mi
      requests:
        memory: 2Mi
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  resources:
    limits:
      memory: 230Mi
    requests:
      memory: 33Mi

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

server:
  grpc_server_max_recv_msg_size: 41943040
  grpc_server_max_send_msg_size: 41943040

storage:
  trace:
    backend: s3
    s3:
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
      bucket: "{{ grafanatempo.s3.bucket }}"
      endpoint: "{{ s3.endpoint | regex_replace('http(.)?://', '') }}"
      region: "{{ s3.region }}"
      insecure: false

global_overrides:
  max_bytes_per_trace: 50000000

memcached:
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  resources:
    limits:
      memory: 96Mi
    requests:
      memory: 2Mi

metaMonitoring:
  serviceMonitor:
    enabled: true
    interval: "{{ grafanatempo.metaMonitoring.serviceMonitor.interval }}"
    scrapeTimeout: "{{ grafanatempo.metaMonitoring.serviceMonitor.scrapeTimeout }}"
