# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

global:
  dnsService: "coredns"
fullnameOverride: loki-distributed

loki:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 2.9.6
    pullPolicy: IfNotPresent
  server:
    http_listen_port: 3100
  configAsSecret: true

  schemaConfig:
    configs:
    - from: "2020-09-01"
      store: tsdb
      object_store: aws
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

  storageConfig:
    tsdb_shipper:
      shared_store: aws
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 168h
    aws:
      bucketnames: {{ loki.bucket }}
      endpoint: {{ s3.endpoint }}
      region: {{ s3.region }}
      access_key_id: {{ s3.access_key }}
      secret_access_key: {{ s3.secret_key }}
      insecure: false
      sse_encryption: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
        insecure_skip_verify: false
      s3forcepathstyle: true

serviceMonitor:
  enabled: true
  scheme: http

prometheusRule:
  enabled: false

ingester:
  replicas: 3
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 2.9.6
  extraArgs: 
    - -config.expand-env=true
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi

  maxUnavailable: 3
  persistence:
    enabled: true
    inMemory: false
    claims:
      - name: data
        size: 20Gi
        storageClass: csi-cinder-high-speed-retain
    enableStatefulSetAutoDeletePVC: false
    whenDeleted: Retain
    whenScaled: Retain
  affinity: |         
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists

distributor:
  replicas: 3
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 2.9.6
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
  resources: 
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  maxUnavailable: 3
  affinity: |         
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

querier:
  replicas: 3
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 2.9.6
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 128Mi
  maxUnavailable: 3
  persistence:
    enabled: true
    size: 20Gi
    storageClass: csi-cinder-high-speed-retain
  max_concurrent: 16
  affinity: |         
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists

queryFrontend:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 2.9.6
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 40m
      memory: 64Mi
  maxUnavailable: 3
  affinity: |         
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists

compactor:
  kind: StatefulSet
  replicas: 3
  enabled: true
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 2.9.6
  extraArgs:
    - -config.expand-env=true
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 64Mi
  affinity: |         
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists

memcachedExporter:
  enabled: true
  image:
    registry: docker.io
    repository: prom/memcached-exporter
    tag: v0.13.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 40m
      memory: 64Mi

gateway:
  enabled: true
  affinity: |         
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists
