# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Ansible playbook deployment

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop # pushes on the 'develop' branch
    tags:
      - '**' # new git tags (including hierarchical tags like v1.0/beta)
  workflow_dispatch: # manual trigger

jobs:
  test-deploy:
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: RS-PYTHON/rs-infra-core
          submodules: recursive
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: rs-infra-monitoring
          ref: ${{ github.ref }}
      - name: Install requirements
        run: |
          # Install miniforge
          mkdir -p ~/miniforge3
          wget -q "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" -O ~/miniforge3/miniforge.sh
          bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
          rm -f ~/miniforge3/miniforge.sh

          # Init conda
          ~/miniforge3/bin/conda init bash
          conda update -n base -c defaults conda
          conda create -y -n rspy python=3.11

          # Install Ansible, Terraform, Openstackclient
          conda run -n rspy conda install -y -c conda-forge ansible terraform python-openstackclient passlib boto3 kubernetes-helm kubernetes-client python-kubernetes

          conda run -n rspy ansible-galaxy collection install openstack.cloud amazon.aws kubernetes.core

          ln -s /usr/share/miniconda/envs/rspy/bin/kubectl /usr/local/bin/kubectl
        shell: bash
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        with:
          addons: 'metallb'
          cpus: 4
          memory: 8000m
      - name: "Configure cluster labels, IP and DNS (host + CoreDNS)"
        run: |
          .github/common/resources/configure-cluster.sh "node-role.kubernetes.io/infra=" "iam kube monitoring oauth2-proxy"
        shell: bash
      - name: Deploy minio
        run: |
          # Minio for cloudnative pg and loki/tempo - https://github.com/minio/minio/tree/master/helm/minio#installing-the-chart-toy-setup
          helm repo add minio https://charts.min.io/
          helm repo update minio
          helm install minio minio/minio --namespace minio --set mode=standalone --set replicas=1 --set persistence.enabled=false --set resources.requests.memory=512Mi --set rootUser=s3_access_key,rootPassword=s3_secret_key --set buckets[0].name=rs-cluster-psql,buckets[1].name=rs-cluster-velero,buckets[2].name=rs-cluster-loki-chunks,buckets[3].name=rs-cluster-loki-ruler,buckets[4].name=rs-cluster-tempo --create-namespace --wait
      - name: Generate inventory
        run: |
          .github/common/resources/configure-inventory.sh
          # --- Generate inventory
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook registry.yaml -i inventory/mycluster/hosts.yaml -e ci_mode=true
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook generate_inventory.yaml -i inventory/mycluster/hosts.yaml
        shell: bash
      - name: Deploy the core apps (for real)
        run: |
          # --- Use local cluster issuer instead of Let's Encrypt
          .github/common/resources/configure-local-ca.sh iam:iam kube:default monitoring:monitoring oauth2-proxy:iam
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml
        shell: bash
      - name: Deploy the monitoring apps (check)
        run: |
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook --check apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-infra-monitoring/apps/"]}' -e private_registry=true
        shell: bash
      - name: Deploy the monitoring apps (for real)
        run: |
          sed -i 's!debug: false!debug: true!g' roles/app-installer/defaults/main.yaml
          # Lower the number of loki replicas
          sed -i \
            -e 's!max_concurrent: 4!max_concurrent: 1!g' \
            -e 's!replicas: 3!replicas: 1!g' \
            -e 's!replicas: 2!replicas: 1!g' \
            -e 's!maxUnavailable: 2!maxUnavailable: 0!g' \
            -e 's!maxUnavailable: 1!maxUnavailable: 0!g' \
            rs-infra-monitoring/apps/loki/values.yaml
          # Disable strict podAntiAffinity loki directives that prevent to deploy on a single node
          # see https://github.com/grafana/helm-charts/issues/2709#issuecomment-2839130975
          for path in $(yq eval '.. | select(has("affinity")) | path | join(".")' rs-infra-monitoring/apps/loki/values.yaml); do
            yq eval -i ".$path.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution += [{
              \"labelSelector\": {\"matchLabels\": {\"app.kubernetes.io/component\": \"not-read\"}},
              \"topologyKey\": \"kubernetes.io/hostname\"
            }]" rs-infra-monitoring/apps/loki/values.yaml
          done
          sed -i 's!insecure: false!insecure: true!g' rs-infra-monitoring/apps/tempo-distributed/values.yaml

          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-infra-monitoring/apps/"]}'
        shell: bash
